import {useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Send,Sparkles} from 'lucide-react';
import Layout from '../components/Layout';
import {api} from '../services/api';
import {ErrorBox,Loading} from '../components/UI';

type Message={who:'ai'|'you';text:string};
type TutorReply={message:string;action:string;is_complete:boolean;provider_mode:'real'|'demo'};
type TutorContext={subject:string;concept:string;concept_id:number;active_gap_id:number|null;recommended_intervention:string|null;previous_tutor_turns:Array<{student:string;tutor:string}>};
const welcome=(concept:string,intervention:string|null):Message=>({who:'ai',text:`We will focus on ${concept}${intervention?` using ${intervention.replaceAll('_',' ')}`:''}. Explain what you currently think happens and why. I will ask one question at a time.`});

export default function Tutor(){
 const [params]=useSearchParams();const requestedConcept=Number(params.get('concept'))||0;const requestedGap=Number(params.get('gap'))||0;
 const [messages,setMessages]=useState<Message[]>([]);const [text,setText]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [context,setContext]=useState<TutorContext>();const [mode,setMode]=useState<'real'|'demo'>();
 useEffect(()=>{let cancelled=false;async function load(){setLoading(true);setError('');try{let conceptId=requestedConcept;if(!conceptId){const dashboard=await api<{recommendation:{concept_id:number|null;action_type:string};assessments:Array<{concept_id:number}>}>('/api/student/dashboard');conceptId=dashboard.recommendation.concept_id||dashboard.assessments[0]?.concept_id||0}if(!conceptId)throw new Error('Complete a diagnostic before starting a concept-focused tutor session.');const query=`concept_id=${conceptId}${requestedGap?`&gap_id=${requestedGap}`:''}`;const value=await api<TutorContext>(`/api/student/tutor-context?${query}`);if(cancelled)return;setContext(value);const history=value.previous_tutor_turns.flatMap(t=>([{who:'you' as const,text:t.student},{who:'ai' as const,text:t.tutor}]));setMessages(history.length?history:[welcome(value.concept,value.recommended_intervention)])}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'The tutor context could not be loaded.')}finally{if(!cancelled)setLoading(false)}}load();return()=>{cancelled=true}},[requestedConcept,requestedGap]);
 async function send(e:React.FormEvent){e.preventDefault();const value=text.trim();if(!value||busy||!context)return;setMessages(m=>[...m,{who:'you',text:value}]);setText('');setBusy(true);setError('');try{const r=await api<TutorReply>('/api/ai/tutor',{method:'POST',body:JSON.stringify({concept_id:context.concept_id,gap_id:context.active_gap_id,message:value})});setMessages(m=>[...m,{who:'ai',text:r.message}]);setMode(r.provider_mode);if(r.is_complete)setMessages(m=>[...m,{who:'ai',text:'Your verification evidence has been saved. Return to the dashboard to see your recalculated next step.'}])}catch(e){setError(e instanceof Error?e.message:'The tutor could not respond.')}finally{setBusy(false)}}
 if(loading)return <Layout><Loading label="Loading concept evidence…"/></Layout>;if(!context)return <Layout><ErrorBox message={error}/></Layout>;
 return <Layout><div className="tutor"><header><span><Sparkles/></span><div><p className="eyebrow">SOCRATIC SUPPORT · {context.subject}</p><h1>AI Tutor</h1><p>Adaptive guidance for {context.concept}. {mode&&<small aria-label="AI provider mode">{mode==='real'?'Real AI connected':'Demo mode'}</small>}</p></div></header><div className="chat" aria-live="polite">{messages.map((m,i)=><div className={`message ${m.who}`} key={i}><small>{m.who==='ai'?'CALIBRATE AI':'YOU'}</small><p>{m.text}</p></div>)}{busy&&<div className="message ai"><p>AI Tutor is considering your reasoning…</p></div>}</div>{error&&<p role="alert" className="error">{error}</p>}<form onSubmit={send}><label htmlFor="tutor-input">Your reasoning</label><textarea id="tutor-input" value={text} onChange={e=>setText(e.target.value)} placeholder="Explain what you think happens and why…"/><button className="button" disabled={busy||!text.trim()}>Send <Send/></button></form><Link to="/student">Return to dashboard</Link></div></Layout>
}
